using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using QueueLink.Data;
using QueueLink.Hubs;
using QueueLink.Integrations.Session;
using QueueLink.Models;
using QueueLink.Services;

var builder = WebApplication.CreateBuilder(args);

// ── Logging ──────────────────────────────────────────────────────────
builder.Logging.SetMinimumLevel(LogLevel.Warning);
builder.Logging.AddFilter("Microsoft", LogLevel.Warning);
builder.Logging.AddFilter("Microsoft.Hosting.Lifetime", LogLevel.Information);
builder.Logging.AddFilter("QueueLink", LogLevel.Information);
builder.Logging.AddFilter("Microsoft.AspNetCore.SignalR", LogLevel.Warning);
builder.Logging.AddFilter("Microsoft.AspNetCore.Http.Connections", LogLevel.Warning);

// ── Database ──────────────────────────────────────────────────────────
var connString = builder.Configuration.GetConnectionString("DefaultConnection");
var databaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

if (!string.IsNullOrEmpty(databaseUrl))
{
    var uri = new Uri(databaseUrl);
    var userInfo = uri.UserInfo.Split(':', 2);
    var pgUser = userInfo[0];
    var pgPass = userInfo.Length > 1 ? userInfo[1] : "";
    var pgHost = uri.Host;
    var pgPort = uri.Port > 0 ? uri.Port : 5432;
    var pgDb = uri.AbsolutePath.TrimStart('/');

    connString = $"Host={pgHost};Port={pgPort};Database={pgDb};Username={pgUser};Password={pgPass};SSL Mode=Require;Trust Server Certificate=true";
}

if (string.IsNullOrEmpty(connString))
    throw new InvalidOperationException("Connection string not found. Set DefaultConnection in appsettings.json or DATABASE_URL env var.");

if (!string.IsNullOrEmpty(databaseUrl))
{
    builder.Services.AddDbContext<ApplicationDbContext>(options =>
    {
        options.UseNpgsql(connString);
        options.ConfigureWarnings(w => w.Ignore(Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning));
    });

    builder.Services.AddDataProtection()
        .SetApplicationName("QueueLink")
        .PersistKeysToDbContext<ApplicationDbContext>();
}
else
{
    builder.Services.AddDbContext<ApplicationDbContext>(options =>
    {
        options.UseSqlServer(connString);
        options.ConfigureWarnings(w => w.Ignore(Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.PendingModelChangesWarning));
    });
}

// ── Identity ─────────────────────────────────────────────────────────
builder.Services
    .AddIdentity<ApplicationUser, IdentityRole>(options =>
    {
        options.Password.RequireDigit = true;
        options.Password.RequiredLength = 6;
        options.Password.RequireNonAlphanumeric = false;
        options.Password.RequireUppercase = false;
        options.Password.RequireLowercase = true;
        options.User.RequireUniqueEmail = true;
        options.SignIn.RequireConfirmedEmail = false;
    })
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();

builder.Services.ConfigureApplicationCookie(options =>
{
    options.LoginPath = "/Account/Login";
    options.AccessDeniedPath = "/Account/AccessDenied";
});

// ── Session ──────────────────────────────────────────────────────────
var sessionTimeoutMin = builder.Configuration.GetValue<int?>("Session:TimeoutMinutes") ?? 10080;
var sessionCookieName = builder.Configuration.GetValue<string>("Session:CookieName") ?? "QueueLink.Session";

builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession(options =>
{
    options.Cookie.Name = sessionCookieName;
    options.Cookie.HttpOnly = true;
    options.Cookie.IsEssential = true;
    options.Cookie.SameSite = SameSiteMode.Lax;
    options.IdleTimeout = TimeSpan.FromMinutes(sessionTimeoutMin);
});

builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<IGuestSession, GuestSession>();

// ── SignalR ─────────────────────────────────────────────────────────
builder.Services.AddSignalR();

// ── Services ─────────────────────────────────────────────────────────
builder.Services.AddScoped<IQueueTicketService, QueueTicketService>();

// ── MVC ─────────────────────────────────────────────────────────────
builder.Services.AddControllersWithViews();

var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
builder.WebHost.UseUrls($"http://0.0.0.0:{port}");

var app = builder.Build();

// ── Ensure DataProtectionKeys table exists ──────────────────────────
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    await db.Database.ExecuteSqlRawAsync(@"
        CREATE TABLE IF NOT EXISTS ""DataProtectionKeys"" (
            ""Id"" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            ""FriendlyName"" text NULL,
            ""Xml"" text NULL,
            CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
        );
    ");
}

// ── Ensure floor-plan layout columns exist ─────────────────────────
// These columns are [NotMapped] in the Table model (EF ignores them)
// so they are managed exclusively through raw SQL.  This block creates
// them if missing and spreads stacked tables into a grid so the floor
// plan is usable immediately.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

    // 1. Create columns (idempotent — IF NOT EXISTS is not valid DDL
    // in PostgreSQL for ADD COLUMN, so we use a DO block).
    await db.Database.ExecuteSqlRawAsync(@"
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'Tables' AND column_name = 'LayoutX'
            ) THEN
                ALTER TABLE ""Tables"" ADD COLUMN ""LayoutX"" decimal NOT NULL DEFAULT 50;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'Tables' AND column_name = 'LayoutY'
            ) THEN
                ALTER TABLE ""Tables"" ADD COLUMN ""LayoutY"" decimal NOT NULL DEFAULT 50;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'Tables' AND column_name = 'LayoutW'
            ) THEN
                ALTER TABLE ""Tables"" ADD COLUMN ""LayoutW"" decimal NOT NULL DEFAULT 12;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'Tables' AND column_name = 'LayoutH'
            ) THEN
                ALTER TABLE ""Tables"" ADD COLUMN ""LayoutH"" decimal NOT NULL DEFAULT 9;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'Tables' AND column_name = 'Block'
            ) THEN
                ALTER TABLE ""Tables"" ADD COLUMN ""Block"" varchar(50) NULL;
            END IF;
        END $$;
    ");

    // 2. Spread tables that are all at the default position (50,50).
    // This runs every startup but only touches tables that are still
    // stacked.  Once the owner moves things in the editor the query
    // returns 0 rows and this becomes a no-op.
    await db.Database.ExecuteSqlRawAsync(@"
        UPDATE ""Tables"" AS t
        SET
            ""LayoutX"" = 12 + (rn % 4) * 22,
            ""LayoutY"" = 18 + (rn / 4) * 22,
            ""LayoutW"" = 18,
            ""LayoutH"" = 16
        FROM (
            SELECT ""Id"", ROW_NUMBER() OVER (ORDER BY ""SortOrder"") - 1 AS rn
            FROM ""Tables""
            WHERE ""IsActive"" AND ""LayoutX"" = 50 AND ""LayoutY"" = 50
        ) AS src
        WHERE t.""Id"" = src.""Id"";
    ");
}

// ── Seed data ────────────────────────────────────────────────────────
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
    var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
    await SeedData.InitializeAsync(db, userManager, roleManager);
}

// ── HTTP pipeline ────────────────────────────────────────────────────
var isRailway = !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("PORT"));
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    if (!isRailway) app.UseHsts();
}

if (!isRailway) app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseSession();

app.UseAuthentication();
app.UseAuthorization();

// ── Routes ──────────────────────────────────────────────────────────
app.MapControllerRoute(
    name: "venueDetail",
    pattern: "venue/{slug}",
    defaults: new { controller = "Public", action = "Index" });

app.MapControllerRoute(
    name: "venues",
    pattern: "venues",
    defaults: new { controller = "Public", action = "Browse" });

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}")
    .WithStaticAssets();

app.MapHub<QueueHub>("/queueHub");

app.Run();

public partial class Program { }
